library(MASS)
library(ggplot2)

# gbd
# Generates and graphs a bivariate dataset
# Graphs show density curves and probability curves when 1 of the variables is broken into quartiles
# Created for use with teacher value-added data; axes label names reflect this.
# See usage examples at bottom

# Inputs:

#	n = # of observations

#	var = variance of each dataset (in our case, both datasets
#	have same variance b/c they both measure teacher value-added)

#	covar = covariance of the 2 datasets [modify to adjust r; 
#		this will involve some trial and error]
#	if covar = var, r = 1
#	if covar = 0,	r = 0

#	xlims  = min & max points on x-axis scale

gbd <- function(n, var, covar, xlims)
{

	# Generate data
	Sigma <- matrix(c(var, covar, covar, var),2,2)
	bivariateData <- (mvrnorm(n=n, rep(0, 2), Sigma, empirical = TRUE))
	
	# Print correlation matrix to see if you like the correlation (r)
	print("The correlation coefficient, r, is")
	print(cor(bivariateData)[1,2])
	
	# Bin one of the two samples into quartiles
	rank <- rank(bivariateData[,2])
	percentiles <- rank/length(rank)
	quartiles<-ceiling(4*percentiles)

	# Rank the other sample by percentiles
	rank <- rank(bivariateData[,1])
	percentiles <- rank/length(rank)
	
	# Generate a data frame with all of the data
	# The data frame has columns VA1, VA1_Percentile, VA2, and VA2_Quartile
	value_added	<- data.frame(VA1=bivariateData[,1], VA1_Percentile=percentiles, VA2=bivariateData[,2], VA2_Quartile=quartiles)


	# Plot the density curve of the other sample
	# x axis = raw value, y axis = # of observations
	# Note: modify 'size=' options to change text size
	p1 <- qplot(value_added$VA1, colour=factor(value_added$VA2_Quartile), geom="density",xlab="Teacher EVA in One Class", ylab="Density",xlim=xlims) + scale_colour_discrete(name = "Quartile of State-Test VA in a Second Class") + opts(legend.title=theme_text(size=20)) + opts(legend.text=theme_text(size=20)) + opts(axis.title.y=theme_text(size=25)) + opts(axis.title.x=theme_text(size=25)) + opts(axis.text.y=theme_text(size=20)) + opts(axis.text.x=theme_text(size=20))

	# Plot the probability curve of the other sample
	# x axis = percentile, y axis = probability
	# modify 'size=' options to change text size
	p2 <- qplot(100*value_added$VA1_Percentile, fill=factor(value_added$VA2_Quartile), colour=factor(value_added$VA2_Quartile),geom="density",xlab="EVA Percentile", ylab="Probability VA Will Fall in Given Quartile",xlim=c(0,100),position="fill") + opts(axis.title.y=theme_text(angle=90, size=25)) + opts(axis.title.x=theme_text(size=25)) + opts(legend.title=theme_blank()) + opts(legend.text=theme_text(size=20)) + opts(axis.text.y=theme_text(size=20)) + opts(axis.text.x=theme_text(size=20))

	# Generate unique identifier for the graphs
this_run_name = paste(n, "_", var, "_", covar)

	# Create and save the graphs
	png(paste("density_curves_",this_run_name,".png"), width=1500, height=720)
	print(p1)
	dev.off()

	png(paste("probability_curves_",this_run_name,".png"), width=819, height=720)
	print(p2)
	dev.off()

}

# Here are some usage examples.
# See the graphs generated by these examples at http://mathnerd.teachforus.org/?p=71
# Numbers were chosen to correspond with values suggested by MET data and Jesse Rothstein's analysis (1511 teachers, variance = 0.00674, r=0.327)
# n was increased to 1e5 (100,000) in the first example to show a more perfect correlation for demonstration purposes

# To use, run this code in the R command line:
# source("METvalueAddedFunction.R") [you may need to modify the path]
# gbd(1e5, .00674, .00674, c(-.4,.4))
# gbd(1511, .00674, 0, c(-.4,.4))
# gbd(1511, .00674, .002205, c(-.4,.4))
